<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Domains\Booking\Models\Booking;
use App\Domains\Payment\Models\Payment;
use App\Domains\User\Models\User;
use App\Domains\MasterData\Models\PackageVariant;
use App\Domains\MasterData\Models\Background;
use App\Domains\Booking\Enums\BookingStatus;
use App\Domains\Booking\Enums\PaymentScheme;
use App\Domains\Booking\Enums\BookingSource;
use App\Domains\Payment\Enums\PaymentPurpose;
use App\Domains\Payment\Enums\PaymentStatus;
use Carbon\Carbon;
use Illuminate\Support\Str;

class BookingPaymentDummySeeder extends Seeder
{
    public function run()
    {
        // Menggunakan Spatie Permission untuk mengambil user dengan role 'user'
        $users = User::role('user')->get();
        
        if ($users->isEmpty()) {
            $this->command->error('Tidak ada user dengan role "user". Harap jalankan seeder user terlebih dahulu.');
            return;
        }
        
        $packageVariants = PackageVariant::all();
        $backgrounds = Background::all();
        
        if ($packageVariants->isEmpty() || $backgrounds->isEmpty()) {
            $this->command->error('Tidak ada paket atau background. Jalankan MasterData seeder dulu.');
            return;
        }

        $startDate = Carbon::create(2026, 6, 1);
        $endDate = Carbon::create(2026, 8, 31);
        
        $totalBookings = rand(50, 150);

        for ($i = 0; $i < $totalBookings; $i++) {
            $date = Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp));
            
            // Random start time antara jam 09:00 dan 16:00
            $startHour = rand(9, 16);
            $startMinute = array_rand(array_flip([0, 15, 30, 45]));
            
            $startTime = $date->copy()->setTime($startHour, $startMinute);
            $endTime = $startTime->copy()->addMinutes(array_rand(array_flip([30, 60, 90, 120]))); // Durasi random
            
            $variant = $packageVariants->random();
            $bg = $backgrounds->random();
            $totalPrice = $variant->price;
            
            $status = array_rand(array_flip([
                BookingStatus::PENDING->value,
                BookingStatus::DP_PAID->value,
                BookingStatus::SUCCESS->value,
                BookingStatus::CANCELLED->value,
                BookingStatus::DONE->value,
            ]));
            
            // Menyesuaikan jika status DP_PAID maka skema pastilah DP
            if ($status === BookingStatus::DP_PAID->value) {
                $scheme = PaymentScheme::DP->value;
            } else {
                $scheme = array_rand(array_flip([PaymentScheme::LUNAS->value, PaymentScheme::DP->value]));
            }

            // generate booking code misal BPW-ABC-260717-XYZ
            $bookingCode = 'BPW-' . strtoupper(Str::random(3)) . '-' . $date->format('dmy') . '-' . strtoupper(Str::random(3));

            $booking = Booking::create([
                'user_id' => $users->random()->id,
                'package_variant_id' => $variant->id,
                'background_id' => $bg->id,
                'booking_code' => $bookingCode,
                'booking_date' => $date,
                'start_time' => $startTime,
                'end_time' => $endTime,
                'total_price' => $totalPrice,
                'payment_scheme' => $scheme,
                'status' => $status,
                'reschedule_count' => 0,
                'notes' => 'Generated by Dummy Seeder',
                'gdrive_link' => $status === BookingStatus::DONE->value ? 'https://drive.google.com/dummy' : null,
                'source' => array_rand(array_flip([BookingSource::FRONTDOOR->value, BookingSource::MANUAL->value])),
            ]);

            // Create Payment berdasarkan relasi status
            $amountDP = $totalPrice * 0.5;

            if ($scheme === PaymentScheme::LUNAS->value) {
                if (in_array($status, [BookingStatus::SUCCESS->value, BookingStatus::DONE->value])) {
                    $this->createPayment($booking, PaymentPurpose::LUNAS, $totalPrice, PaymentStatus::SETTLEMENT, $date->copy()->subDays(1));
                } elseif ($status === BookingStatus::PENDING->value) {
                    $this->createPayment($booking, PaymentPurpose::LUNAS, $totalPrice, PaymentStatus::PENDING, null);
                } elseif ($status === BookingStatus::CANCELLED->value) {
                    $this->createPayment($booking, PaymentPurpose::LUNAS, $totalPrice, PaymentStatus::CANCELLED, null);
                }
            } else { // Jika DP
                if ($status === BookingStatus::PENDING->value) {
                    $this->createPayment($booking, PaymentPurpose::DP, $amountDP, PaymentStatus::PENDING, null);
                } elseif ($status === BookingStatus::DP_PAID->value) {
                    $this->createPayment($booking, PaymentPurpose::DP, $amountDP, PaymentStatus::SETTLEMENT, $date->copy()->subDays(2));
                    $this->createPayment($booking, PaymentPurpose::PELUNASAN, $totalPrice - $amountDP, PaymentStatus::PENDING, null);
                } elseif (in_array($status, [BookingStatus::SUCCESS->value, BookingStatus::DONE->value])) {
                    $this->createPayment($booking, PaymentPurpose::DP, $amountDP, PaymentStatus::SETTLEMENT, $date->copy()->subDays(2));
                    $this->createPayment($booking, PaymentPurpose::PELUNASAN, $totalPrice - $amountDP, PaymentStatus::SETTLEMENT, $date->copy()->subDays(1));
                } elseif ($status === BookingStatus::CANCELLED->value) {
                    $this->createPayment($booking, PaymentPurpose::DP, $amountDP, PaymentStatus::CANCELLED, null);
                }
            }
        }

        $this->command->info("Berhasil membuat {$totalBookings} data dummy Booking dan Payment dari Juni hingga Agustus 2026.");
    }

    private function createPayment($booking, $purpose, $amount, $status, $payDate)
    {
        Payment::create([
            'booking_id' => $booking->id,
            'order_id' => 'ORD-' . $booking->booking_code . '-' . strtoupper(Str::random(4)),
            'payment_type' => 'bank_transfer',
            'payment_purpose' => $purpose->value,
            'amount' => $amount,
            'status' => $status->value,
            'pay_date' => $payDate,
            'snap_token' => Str::random(20),
            'snap_token_expiry' => now()->addDay(),
        ]);
    }
}
